before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libgmime-2.6-dev
  - sudo apt-get install libgmime2.6-cil
  - sudo apt-get install libglib2.0-dev
  - sudo apt-get install libgmime2.6-cil-dev
language: go
go:
  - master
script: go test -cover -bench=. -v github.com/sendgrid/go-gmime/gmime
